// Generated by https://quicktype.io

export interface Noticia {
    id:          number;
    titulo:      NoticiaTitulo;
    enlace?:      string;
    idCategoria: number;
    foto?:        string;
    createdAt:   string;
    updatedAt:   string;
    secciones?:   Seccion[];
}

export interface Seccion {
    id:        number;
    idNoticia: number;
    titulo?:    string;
    texto?:     string;
    foto?:      string;
    createdAt: string;
    updatedAt: string;
    enlaces?:   Enlace[];
}

export interface Enlace {
    id:         number;
    idSeccion:  number;
    textoClave: string;
    url:        string;
    createdAt:  string;
    updatedAt:  string;
}

export enum Texto {
    Texto = "texto",
}

export enum SeccioneTitulo {
    Seccion = "Seccion",
}

export enum NoticiaTitulo {
    Noticia = "noticia",
}
